### ISSUE TITLE
Error while installing ali

### ISSUE THREAD

**Issue by xcyan** [IshmaelBelghazi/ALI#1]
$ pip install -e ali
$ Directory 'ali' is not installable. File 'setup.py' not found.

Any ideas of the reason? Thanks!

**Comment by vdumoulin** [comment]
I think there's a typo in the instruction. Could you try

```
pip install -e ALI
```

and tell me if it works?

**Comment by xcyan** [comment]
that works, thanks!

**Comment by IshmaelBelghazi** [comment]
Thanks guys. Closing the issue.
