### ISSUE TITLE
deserialization of models hangs

### ISSUE THREAD

**Issue by dribnet** [IshmaelBelghazi/ALI#2]
Training goes well for me using the scripts in `experiments` with the latest version of blocks, but then when I run any subsequent command that uses the generated model like `scripts/sample` or `scripts/reconstruct`, the command hangs indefinitely. My guess is that the deserialization is getting jammed up.

I can look into it more - not yet familiar with the new tar format - but curious if this might be a known issue.

**Comment by dribnet** [comment]
update: got it working on linux, so it seems to be mac specific.

**Comment by dribnet** [comment]
Ahem, so the "hang" was really just a window being opened on a remote computer. Sorry for the false alarm - `--save-path` is working great, closing.
![ali_svhn](https://cloud.githubusercontent.com/assets/945979/16329734/674a6a48-3a38-11e6-85a2-cd7cc9d908fd.png)

**Comment by vdumoulin** [comment]
That's reassuring, thanks for letting us know!
